name: Deploy to shimmergem.github.io
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        REPOSITORY_NAME: shimmergem/shimmergem
        BRANCH: production
        FOLDER: dist
        BUILD_SCRIPT: npm install && npx webpack